1. Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [79]:
import pandas as pd
import numpy as np

# Part 1: Create a Pandas Series
lst = [10, 20, 30, 40, 50]

series = pd.Series(lst)

print("Series:")
print(series)

print("\nIndex:")
# print(series.index)
index = list(series.index)
print(index)

print("\nData Type:")
print(series.dtype)


# Part 2: Create a Pandas DataFrame
newDF = pd.DataFrame(
    [
        ["Amit Hasan", 23, "Dhaka"],
        ["Shaikot", 30, "Noakhali"],
        ["Rahim", 22, "Chittagong"],
        ["Karim", 25, "Sylhet"]
    ],
    columns=["Name", "Age", "City"]
)

print("\nDataFrame:")
print(newDF)

Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Index:
[0, 1, 2, 3, 4]

Data Type:
int64

DataFrame:
         Name  Age        City
0  Amit Hasan   23       Dhaka
1     Shaikot   30    Noakhali
2       Rahim   22  Chittagong
3       Karim   25      Sylhet

2.Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), and summary statistics (.describe()).

In [80]:
# Number of rows and columns
print("Rows:", newDF.shape[0])
print("Columns:", newDF.shape[1])

# Data types of each column
print("\nColumn Data Types:")
print(newDF.dtypes)

# Summary statistics
print("\nSummary Statistics:")
print(newDF.describe(include="all"))
# print(newDF.describe())

Rows: 4
Columns: 3

Column Data Types:
Name    object
Age      int64
City    object
dtype: object

Summary Statistics:
              Name        Age   City
count            4   4.000000      4
unique           4        NaN      4
top     Amit Hasan        NaN  Dhaka
freq             1        NaN      1
mean           NaN  25.000000    NaN
std            NaN   3.559026    NaN
min            NaN  22.000000    NaN
25%            NaN  22.750000    NaN
50%            NaN  24.000000    NaN
75%            NaN  26.250000    NaN
max            NaN  30.000000    NaN

3.Create a DataFrame using the dictionary below:


data = {
    <br>'Product': ['Pen', 'Book', 'Eraser', 'Pencil'], <br>
    'Price': [10, 50, 5, 7], <br>
    'Quantity': [100, 60, 200, 150]
}

Print .columns, .index. Access a single column and one full row.

In [81]:

data = {
  'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
  'Price': [10, 50, 5, 7],
  'Quantity': [100, 60, 200, 150]
  }
df = pd.DataFrame(data)
print(np.array(df.columns))
print(np.array(df.index))
print(df.loc[:,"Product"])
df.loc[0:0]

['Product' 'Price' 'Quantity']
[0 1 2 3]
0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

  Product  Price  Quantity
0     Pen     10       100

4.. Using .loc[] and .iloc[], show the first row, the second column, and a 2×2 block    from the middle of your DataFrame.

In [106]:
# 1. Access the first row using .loc[]
# .loc[] uses index labels; the ending label is included.
print("First row using loc:")
print(df.loc[0:0])


# 2. Access the first row using .iloc[]
# .iloc[] uses integer positions; the ending position is excluded.
print("\nFirst row using iloc:")
print(df.iloc[0:1])


# 3. Access the second column using .loc[]
# Select all rows (:) and the column named "Price".
print("\nSecond column using loc:")
print(df.loc[:, "Price"])


# 4. Access the second column using .iloc[]
# : means all rows; 1:2 selects the column at position 1.
print("\nSecond column using iloc:")
print(df.iloc[:, 1:2])


# 5. Access a 2×2 block using .loc[]
# Select rows with labels 1 and 2,
# and columns from "Product" through "Price", inclusive.
print("\n2×2 block using loc:")
print(df.loc[1:2, "Product":"Price"])


# 6. Access a 2×2 block using .iloc[]
# Select rows at positions 1 and 2,
# and columns at positions 0 and 1.
print("\n2×2 block using iloc:")
print(df.iloc[1:3, 0:2])

First row using loc:
  Product  Price  Quantity
0     Pen     10       100

First row using iloc:
  Product  Price  Quantity
0     Pen     10       100

Second column using loc:
0    10
1    50
2     5
3     7
Name: Price, dtype: int64

Second column using iloc:
   Price
0     10
1     50
2      5
3      7

2×2 block using loc:
  Product  Price
1    Book     50
2  Eraser      5

2×2 block using iloc:
  Product  Price
1    Book     50
2  Eraser      5

5.. Create a 4×3 DataFrame of student names and marks. Drop one column using .drop(), drop one row by index

In [110]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Amit", "Rahim", "Karim", "Shaikot"],
    "Math": [85, 90, 78, 88],
    "Science": [80, 92, 75, 86]
})

print(df)
print("Shape:", df.shape)

df.drop("Science", axis=1, inplace=True)
df.drop(2, inplace=True)
df

      Name  Math  Science
0     Amit    85       80
1    Rahim    90       92
2    Karim    78       75
3  Shaikot    88       86
Shape: (4, 3)

      Name  Math
0     Amit    85
1    Rahim    90
3  Shaikot    88


6.Create a DataFrame of employees with columns "Name", "Department", and "Salary". Sort it by "Salary" in ascending order and by "Name" in descending order.

In [111]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Amit", "Rahim", "Karim", "Nadia"],
    "Department": ["IT", "HR", "Finance", "IT"],
    "Salary": [50000, 40000, 45000, 55000]
})

print(df)
df.sort_values(['Salary','Name'], ascending=[1,0])

    Name Department  Salary
0   Amit         IT   50000
1  Rahim         HR   40000
2  Karim    Finance   45000
3  Nadia         IT   55000

    Name Department  Salary
1  Rahim         HR   40000
2  Karim    Finance   45000
0   Amit         IT   50000
3  Nadia         IT   55000

7.Create a DataFrame of 8 students with columns "Name" and "Score". Filter and print students with Score > 60 and those with Score < 40.

In [120]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Amit", "Rahim", "Karim", "Nadia",
             "Sadia", "Hasan", "Rafi", "Mim"],
    "Score": [85, 90, 78, 92, 38, 76, 95, 32]
})

print(df,'\n')
print(df.loc[(df["Score"] > 60)])
df.loc[(df["Score"] < 40)]

    Name  Score
0   Amit     85
1  Rahim     90
2  Karim     78
3  Nadia     92
4  Sadia     38
5  Hasan     76
6   Rafi     95
7    Mim     32

    Name  Score
0   Amit     85
1  Rahim     90
2  Karim     78
3  Nadia     92
5  Hasan     76
6   Rafi     95

    Name  Score
4  Sadia     38
7    Mim     32